// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvbklddpyyuhhvkobkfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2YmtsZGRweXl1aGh2a29ia2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDE1MTQsImV4cCI6MjA2Njc3NzUxNH0.HGA-7a5rDwd7uep0XoXUUu-DqZ0JttqGT5zxLuOEh7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);